---
title: "Alerts"
output: pdf_document
date: "2024-11-20"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Load necessary libraries
```{r}
library(dplyr)
library(ggplot2)
library(lubridate)
library(readr)

ridership_2023 <- read_csv("~/Desktop/School/Software tools for Data Analysis/Project/GSE_2023.csv")
ridership_2024 <- read_csv("~/Desktop/School/Software tools for Data Analysis/Project/GSE_2024.csv")
service_alerts <- read_csv("~/Desktop/School/Software tools for Data Analysis/Project/MBTA_Service_Alerts.csv") 
```


```{r}
ridership <- bind_rows(ridership_2023, ridership_2024)

ridership <- ridership %>%
  mutate(service_date = as.Date(service_date),
         gated_entries = ifelse(gated_entries < 0, NA, gated_entries))  

service_alerts <- service_alerts %>%
  mutate(notif_start = as.Date(notif_start),  
         month = floor_date(notif_start, "month"))  

```

# Top Alert Frequency
```{r}
top_alert_types <- service_alerts %>%
  count(effect_name) %>%
  arrange(desc(n)) %>%
  slice(1:5) %>%
  pull(effect_name)
```

# Only Top Alerts
```{r}
filtered_alerts <- service_alerts %>%
  filter(effect_name %in% top_alert_types)
```

# Top Alert Count
```{r}
monthly_alerts <- filtered_alerts %>%
  group_by(month, effect_name) %>%
  summarise(alert_count = n(), .groups = "drop")
```

# PAST 3 Years
```{r}
start_date <- as.Date("2021-01-01")
monthly_alerts <- monthly_alerts %>% filter(month >= start_date)
```

#Visulization
```{r}
graph<- ggplot(monthly_alerts, aes(x = month, y = alert_count, fill = effect_name)) +
  geom_bar(stat = "identity", position = "stack") +
  labs(title = "Monthly Frequency of All Top Alert Types (Last 3 Years)",
       x = "Month",
       y = "Alert Frequency",
       fill = "Alert Type") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
graph
```


```{r Graph, echo=FALSE}
plot(graph)
```
